### PR TITLE
Fix broken pip install

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
`pip install .` fails with recent versions of Python3 / pip. See discussion at https://github.com/OCR-D/ocrd_all/pull/400.

This patch provides a fast fix. I think a better one would integrate metadata from setup.cfg into pyproject.toml.

**Comment by kba** [comment]
> `pip install .` fails with recent versions of Python3 / pip. See discussion at [OCR-D/ocrd_all#400](https://github.com/OCR-D/ocrd_all/pull/400).

This is what I would have done, but ...

> This patch provides a fast fix. I think a better one would integrate metadata from setup.cfg into pyproject.toml.

... this is what I would have recommended :-)

So agree, we should move most if not all the metadata from `setup.cfg` to the `[project]` table of `pyproject.toml`.

**Review by kba — APPROVED** [review]

**Comment by bertsky** [comment]
Wow. That issue really caught me by surprise. We were following quite recent guidelines regarding modernized packaging, only to find out that this has [already become unsupported by setuptools](https://setuptools.pypa.io/en/latest/history.html#deprecations-and-removals) now. 

Official documentation on this is still poor: 
- https://packaging.python.org/en/latest/guides/writing-pyproject-toml still just says
   > Also, the [setuptools](https://setuptools.pypa.io/) build backend supports both the [project] table, and the older format in setup.cfg or setup.py.
- https://packaging.python.org/en/latest/guides/single-sourcing-package-version just says
   > As of the release of setuptools 61.0.0, one can specify the version dynamically in the project’s pyproject.toml file.
- https://pypi.org/project/setuptools-scm does not mention setup.cfg at all

So I now understand that because we do need __dynamic__ version, we cannot use setup.cfg anymore! (I believe this issue will affect lots of other packages we manage, too.)

Thanks for the workaround, @stweil! It seems to work, but I would also prefer migrating from setup.cfg. So let's keep this open for current ocrd_all, but I'll draft a new PR along those lines.

**Comment by bertsky** [comment]
superseded by #14

**Pull request closed without merging**
